### PR TITLE
Add documents for query language, Let query package support put and remove statements

### PR DESCRIPTION
**Pull request by blacktear23**
Add documents for query language

### CODE REVIEW

**Comment by c4pt0r** [comment]
Hello, I am a [serverless review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/). Here are my reviews of code commits in this PR.

------

**Comment by c4pt0r** [comment]
Since I've already merged in the vector-related functions, please add the related functions to the Function list as well

**Comment by c4pt0r** [comment]
After merging this PR, I will update the README.

**Comment by blacktear23** [comment]
Also add put and remove statement support.

**Pull request merged**
